from pydantic import BaseModel, field_validator
from typing import Optional, Union
from datetime import date
from enum import Enum


class VisaType(str, Enum):
    F1 = "F-1"
    J1 = "J-1"


class EnrollmentStatus(str, Enum):
    FULL_TIME = "full_time"
    PART_TIME = "part_time"
    ON_BREAK = "on_break"


def _normalize_enrollment(v: Union[str, EnrollmentStatus]) -> EnrollmentStatus:
    if isinstance(v, EnrollmentStatus):
        return v
    m = {"full_time": EnrollmentStatus.FULL_TIME, "Full-time": EnrollmentStatus.FULL_TIME,
         "part_time": EnrollmentStatus.PART_TIME, "Part-time": EnrollmentStatus.PART_TIME,
         "on_break": EnrollmentStatus.ON_BREAK, "On break": EnrollmentStatus.ON_BREAK}
    return m.get(v, EnrollmentStatus.FULL_TIME)


class StudentProfileCreate(BaseModel):
    """Request body for POST /student/profile; student_id is generated by the server."""
    full_name: str
    university: str
    country_of_origin: str
    visa_type: VisaType
    program_start_date: date
    program_end_date: date
    enrollment_status: EnrollmentStatus
    weekly_work_hours: float
    on_opt: bool
    on_cpt: bool
    opt_start_date: Optional[date] = None
    opt_end_date: Optional[date] = None
    cpt_start_date: Optional[date] = None
    cpt_end_date: Optional[date] = None
    traveling_soon: bool
    changing_employer: bool
    changing_courses: bool

    @field_validator("enrollment_status", mode="before")
    @classmethod
    def normalize_enrollment(cls, v: Union[str, EnrollmentStatus]) -> EnrollmentStatus:
        return _normalize_enrollment(v)


class StudentProfile(BaseModel):
    student_id: str
    full_name: str
    university: str
    country_of_origin: str
    visa_type: VisaType
    program_start_date: date
    program_end_date: date
    enrollment_status: EnrollmentStatus
    weekly_work_hours: float  # on-campus work hours per week
    on_opt: bool
    on_cpt: bool
    opt_start_date: Optional[date] = None
    opt_end_date: Optional[date] = None
    cpt_start_date: Optional[date] = None
    cpt_end_date: Optional[date] = None
    traveling_soon: bool  # within 90 days
    changing_employer: bool
    changing_courses: bool
